#!/usr/bin/env bash
# Configures server to meet 0x0F requirements
sudo apt-get update
sudo apt-get install nginx -y
sudo echo "Hello World!" | sudo tee "/var/www/html/index.html"
sudo ufw allow 'NGINX HTTP'
sudo sed -i "24 i \\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-enabled/default
sudo sed -i "27 i \\\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default
sudo service nginx restart
