#!/usr/bin/env bash
# Configure and install HAproxy on lb-01 server

sudo apt-get update
sudo apt-get -y install haproxy

sudo sed -i "$ aENABLED=1" /etc/default/haproxy
sudo echo "
frontend webfrontend
	bind *:80
	mode http
	default_backend web-backend

backend web-backend
	balance roundrobin
	server 3276-web-01 35.229.80.162:80 check
	server 3267-web-02 54.234.73.229:80 check" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart

