#!/usr/bin/env bash
# Creates a file, displays message, deletes it and terminates process

echo "$$" > /var/run/myscript.pid

while true; do
	echo "To infinity and beyond"
	sleep 2
	trap "echo 'I hate the kill command'; rm /var/run/myscript.pid; exit" SIGTERM
	trap "rm /var/run/myscript.pid; exit" SIGQUIT
	trap "echo 'Y U no love me?!'" SIGINT
done
