#!/usr/bin/env bash
# read and cut script
# daemon:x:1:1:daemon:/usr/sbin
# out of the above i want daemon:1:/usr/sbin (first number1)

filename="etc/passwd"

while IFS= read -r line; do
	cut -d: -f 1,3,6 "$line" | cat
done < "$filename"
