#!/usr/bin/env bash
# read and cut script
# daemon:x:1:1:daemon:/usr/sbin
# out of the above i want daemon:1:/usr/sbin (first number1)

filename="etc/passwd"

while IFS=: read -r username password userid groupid comment homedir; do
	echo "$username:$userid:$homedir"
done < "$filename"
