#!/usr/bin/env bash
# Sets up firewall for web-01
# Blocks all incoming traffic except ports from line 8 to 10

sudo ufw disable
sudo ufw default deny incoming
sudo ufw allow 22/tcp
sudo ufw allow 80/tcp
sudo ufw allow 443/tcp
sudo ufw enable
